config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :properties do
    get :generate_final_template, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  mount_base64_uploader :path, PictureUploader

  def detect_geo_coordinates
    require 'exiftool'

    e = Exiftool.new(path.file.file)
    exif = e.to_hash.slice(:gps_longitude, :gps_latitude)

    return exif.values if [:gps_longitude, :gps_latitude].all? {|s| exif.key? s }

    # Amsterdam coast
    [4.4752, 52.2702]
  end

end

app/models/photos_analyzer.rb
class PhotosAnalyzer

  def self.recognize(photo_path)
    cmd = TTY::Command.new
    tensor_path = [Rails.root,'lib','tensor_models','tutorials','image','imagenet'].join('/')
    out,err = cmd.run("cd #{tensor_path} && python3 classify_image.py --image_file=#{photo_path}")
    result = []
    out.split(', ').map{|i|
      i.split("\n").map{|y| 
        stuff, score = y.split(' (score = ')
        result << stuff if score.nil? or score.to_f > 0.1
      }
    }
    result
  end

end

app/models/photos_to_property_parser.rb
class PhotosAnalyzer

  def self.recognize(photo_path)
    cmd = TTY::Command.new
    tensor_path = [Rails.root,'lib','tensor_models','tutorials','image','imagenet'].join('/')
    out,err = cmd.run("cd #{tensor_path} && python3 classify_image.py --image_file=#{photo_path}")
    result = []
    out.split(', ').map{|i|
      i.split("\n").map{|y| 
        stuff, score = y.split(' (score = ')
        result << stuff if score.nil? or score.to_f > 0.1
      }
    }
    result
  end

end

app/models/property.rb
class Property < ApplicationRecord

  has_many :rooms

  def generate_final_template
    process_rooms_photos
    geo_coordinates   = rooms.to_a.map(&:photos).flatten.first.detect_geo_coordinates
    price_per_night   = generate_price_per_night(geo_coordinates)
    address           = detect_address(geo_coordinates)
    {
      id: id,
      address: address,
      rooms: rooms,
      price_per_night: price_per_night
    }
  end

  def process_rooms_photos
    rooms.to_a.map(&:process_photos!)
  end

  def generate_price_per_night(geo_coordinates)
    region_url  = "http://search.leisure-ict.com/api/v1/properties?distance=50&exact_location=0&latitude=#{geo_coordinates.last}&longitude=#{geo_coordinates.first}"
    result      = JSON.parse(RestClient.get(region_url))
    region_code = result["properties"].first["country_regions"].first['code']
    
    price_url   = "http://search.leisure-ict.com/api/v1/properties?region_id=#{region_code}&per_page=200"
    result      = JSON.parse(RestClient.get(price_url))
    prices      = result['properties'].map{|p| p['price']['price']}
    
    average_price = prices.sum / prices.size.to_f
    average_price = (average_price / 7.0).round
    average_price - (average_price * 0.20)
  end

  def detect_address(geo_coordinates)
    if data = Geocoder.search(geo_coordinates.reverse).first.try(:data)
      {
        country: data['address']['country'],
        region: data['address']['state'],
        city: data['address']['city'],
      }
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :property
  has_many :photos
  attr_accessor :photo_data

  def as_json(attrs={})
    {
      name: name,
      amenities: amenities.split(','),
      photos: photos.to_a.map{|p| p.path }
    }
  end

  def process_photos!
    self.amenities = photos.to_a.map{|p| PhotosAnalyzer.recognize(p.path.path) }.flatten.join(',')
    self.save
    self.amenities
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy, :generate_final_template]
  skip_before_action :verify_authenticity_token

  def generate_final_template
    final_template = @property.generate_final_template
    render json: final_template
  end

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render json: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property_id, :room, :geo_location, :description)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        params[:photo_data].each do |file|
          @room.photos.create!(:path => file)
        end

        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render json: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.permit(:property_id, :name, :amenities, :photo_data => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pixtalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room %>
  </div>

  <div class="field">
    <%= form.label :geo_location %>
    <%= form.text_field :geo_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Rooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property_id %></td>
        <td><%= property.rooms.count %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property.property_id %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @property.rooms.pluck(:name).join(', ') %>
</p>

<p>
  <strong>Persons:</strong>
  <%= @property.persons %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @property.price_per_night %>
</p>

<p>
  <strong>Geo location:</strong>
  <%= @property.geo_coordinates %>
</p>

<p>
  <strong>General Amenities:</strong>
  <%= @property.general_amenities %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amenities %>
    <%= form.text_area :amenities %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Name</th>
      <th>Amenities</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.property.property_id %></td>
        <td><%= room.name %></td>
        <td><%= room.amenities %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @room.property.property_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Amenities:</strong>
  <%= @room.amenities %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>